# Builds the Hypnic Teen APK using the Android SDK tools directly.
#
#   powershell -File android\build.ps1              the build you hand out
#   powershell -File android\build.ps1 -Testing     same, but inspectable
#
# No Gradle, no wrapper download, no plugin version matching — just aapt2,
# javac, d8, zipalign and apksigner, all of which ship with the SDK you already
# have installed. Output: android\out\HypnicTeen.apk
#
# -Testing turns on WebView remote debugging, which is what lets the automated
# device check drive the page. Anyone with a USB cable and developer mode could
# use the same door to inspect the app, so the default build leaves it shut.

param([switch]$Testing)

$ErrorActionPreference = 'Stop'

$SDK      = if ($env:ANDROID_SDK) { $env:ANDROID_SDK } else { 'W:\Android_SDK' }
$JBR      = if ($env:ANDROID_JBR) { $env:ANDROID_JBR } else { 'W:\Anroid Studio\jbr' }
$here     = Split-Path -Parent $MyInvocation.MyCommand.Path
$build    = Join-Path $here 'build'
$out      = Join-Path $here 'out'

# Pick the newest build-tools and platform present, rather than pinning one.
$bt       = (Get-ChildItem "$SDK\build-tools" -Directory | Sort-Object Name -Descending | Select-Object -First 1).FullName
$platform = (Get-ChildItem "$SDK\platforms" -Directory | Where-Object { Test-Path "$($_.FullName)\android.jar" } |
             Sort-Object Name -Descending | Select-Object -First 1).FullName
$androidJar = Join-Path $platform 'android.jar'

foreach ($p in @($SDK, $JBR, $bt, $androidJar)) {
  if (-not (Test-Path $p)) { throw "Not found: $p" }
}

# d8 and apksigner are .bat wrappers that look for JAVA_HOME. Point them at the
# JDK bundled with Android Studio so nothing has to be installed system-wide.
$env:JAVA_HOME = $JBR

Write-Host "  SDK        $SDK"
Write-Host "  build-tools$([char]9)$(Split-Path -Leaf $bt)"
Write-Host "  platform   $(Split-Path -Leaf $platform)"
Write-Host ""

Remove-Item $build -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $build, "$build\classes", "$build\gen", "$build\dex", $out | Out-Null

# 1 ── resources
Write-Host "  [1/6] compiling resources"
& "$bt\aapt2.exe" compile --dir "$here\res" -o "$build\res.zip"
if ($LASTEXITCODE) { throw "aapt2 compile failed" }

Write-Host "  [2/6] linking resources"
& "$bt\aapt2.exe" link `
  -o "$build\base.apk" `
  -I $androidJar `
  --manifest "$here\AndroidManifest.xml" `
  -R "$build\res.zip" `
  --java "$build\gen" `
  --min-sdk-version 24 `
  --target-sdk-version 36 `
  --auto-add-overlay
if ($LASTEXITCODE) { throw "aapt2 link failed" }

# The one thing that differs between the two builds, written as a constant so
# the switch is visible in the source rather than hidden in a build argument.
$flagDir = "$build\gen\com\hypnicteen\funworld"
New-Item -ItemType Directory -Force -Path $flagDir | Out-Null
@"
package com.hypnicteen.funworld;

/** Generated by android/build.ps1 — do not edit. */
final class BuildFlags {
    /** WebView remote debugging. On only for -Testing builds. */
    static final boolean WEB_DEBUG = $($Testing.IsPresent.ToString().ToLower());
}
"@ | Set-Content "$flagDir\BuildFlags.java" -Encoding ascii  # utf8 here means a BOM, which javac rejects

# 2 ── java
Write-Host "  [3/6] compiling java"
$sources = @()
$sources += (Get-ChildItem "$here\src" -Recurse -Filter *.java | ForEach-Object { $_.FullName })
$sources += (Get-ChildItem "$build\gen" -Recurse -Filter *.java | ForEach-Object { $_.FullName })
# Modern javac refuses -bootclasspath together with -target, and it isn't
# needed: android.jar on the classpath is what resolves the framework, and d8
# desugars the rest.
& "$JBR\bin\javac.exe" -nowarn -source 17 -target 17 `
  -classpath $androidJar -d "$build\classes" $sources
if ($LASTEXITCODE) { throw "javac failed" }

# 3 ── dex
Write-Host "  [4/6] dexing"
$classes = Get-ChildItem "$build\classes" -Recurse -Filter *.class | ForEach-Object { $_.FullName }
& "$bt\d8.bat" --min-api 24 --lib $androidJar --output "$build\dex" $classes
if ($LASTEXITCODE) { throw "d8 failed" }

# 4 ── package: drop the dex into the resource-only apk
Write-Host "  [5/6] packaging"
Copy-Item "$build\base.apk" "$build\unsigned.apk" -Force
Push-Location "$build\dex"
& "$JBR\bin\jar.exe" uf "$build\unsigned.apk" classes.dex
Pop-Location
if ($LASTEXITCODE) { throw "packaging failed" }

& "$bt\zipalign.exe" -f -p 4 "$build\unsigned.apk" "$build\aligned.apk"
if ($LASTEXITCODE) { throw "zipalign failed" }

# 5 ── sign. A local keystore is fine: this is sideloaded, not Play-published.
$keystore = Join-Path $here 'hypnic.keystore'
if (-not (Test-Path $keystore)) {
  Write-Host "  ...creating signing key (first run only)"
  & "$JBR\bin\keytool.exe" -genkeypair -v `
    -keystore $keystore -alias hypnic `
    -storepass hypnicteen -keypass hypnicteen `
    -keyalg RSA -keysize 2048 -validity 10000 `
    -dname "CN=Hypnic Teen, OU=Fun World, O=Hypnic Teen Studio, C=IN" | Out-Null
}

Write-Host "  [6/6] signing"
# Separate filenames so the inspectable build can never be the one you send.
$apk = Join-Path $out $(if ($Testing) { 'HypnicTeen-test.apk' } else { 'HypnicTeen.apk' })
& "$bt\apksigner.bat" sign `
  --ks $keystore --ks-pass pass:hypnicteen --key-pass pass:hypnicteen `
  --out $apk "$build\aligned.apk"
if ($LASTEXITCODE) { throw "apksigner failed" }

& "$bt\apksigner.bat" verify $apk | Out-Null
if ($LASTEXITCODE) { throw "signature verification failed" }

$size = [math]::Round((Get-Item $apk).Length / 1KB, 0)
Write-Host ""
Write-Host "  Built $apk  ($size KB)" -ForegroundColor Green
if ($Testing) {
  Write-Host "  Inspectable build, for 'npm run device-test'. Do not hand this one out." -ForegroundColor Yellow
} else {
  Write-Host "  Send that file to your friends. They tap it and allow 'install from unknown sources'."
}
Write-Host ""
